### ISSUE TITLE
Crash when heading to LightFoot Village from ThornTail Hollow

### ISSUE THREAD

**Issue by RenaKunisaki** [RenaKunisaki/StarFoxAdventures#3]
(Split from #1)

The game runs out of memory and crashes when jumping into the pond in this area.

This should be fixed by the new allocator tweaks in v1.7.

**Comment by RenaKunisaki** [comment]
Seems to be fixed by 2eecd5abb25b80bad4aca4252c1571d93a4e3acb.

**Comment by extherian** [comment]
I've compiled the new script, which does indeed produce the proper ISO size of 1.35 GB. I will be testing it on the latest version of Dolphin and will let you know if there's any more crashes.

**Comment by RenaKunisaki** [comment]
Is this still happening?

**Comment by extherian** [comment]
Nope, no crashes so far. You can close this issue if you like, I'll report back if it crashes again anywhere.

On an unrelated note, would you mind deleting the save file I sent you from your computer, since the in-game file uses my initials? Obviously I can't verify if you actually follow through with this or not, but I thought I'd ask all the same.

**Comment by RenaKunisaki** [comment]
Yeah, I'll get rid of it.
